-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 516cc9fa72ad09699f2c03ffbd0aa7f60d75b59a
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: tests/(inputs|outputs)
    -   id: autopep8-wrapper
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: flake8
-   repo: git@github.com:pre-commit/pre-commit
    sha: 2c70476c63f912bb53f914c94d102ef9032bc407
    hooks:
    -   id: validate_config
    -   id: validate_manifest
-   repo: git@github.com:asottile/reorder_python_imports
    sha: 3d86483455ab5bd06cc1069fdd5ac57be5463f10
    hooks:
    -   id: reorder-python-imports
