#!/usr/bin/env python
from __future__ import absolute_import
from __future__ import unicode_literals

import sys

from Cheetah.compile import compile_file
from Cheetah import five

from cheetah_lint.flake import AllMacrosTrivialCompiler


# This script is useful for testing templates and looking at the intermediate
# python output


def compile_template(filename):
    if not isinstance(filename, five.text):
        filename = filename.decode('UTF-8')
    return compile_file(
        filename,
        settings={'useNameMapper': False},
        compiler_cls=AllMacrosTrivialCompiler,
    )


def compile_all(filenames):
    for filename in filenames:
        compile_template(filename)


def main():  # pragma: no cover (called by commandline only)
    compile_all(sys.argv[1:])


if __name__ == '__main__':
    main()
